# Generated by Django 4.2.3 on 2023-07-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Expected salary'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Experience'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_education',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Education'),
        ),
    ]
