# Generated by Django 4.2.3 on 2023-07-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_expected_salary_user_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expected_salary',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Expected salary'),
        ),
    ]
