# Generated by Django 4.2.3 on 2023-07-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_application_expected_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='expected_salary',
            field=models.FloatField(blank=True, choices=[(0, 'up to 1.000'), (1, 'from 1.000 to 2.000'), (2, 'from 2.000 to 3.000'), (3, 'over 3.000')], max_length=255, null=True, verbose_name='Expected salary'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_range',
            field=models.FloatField(blank=True, choices=[(0, 'up to 1.000'), (1, 'from 1.000 to 2.000'), (2, 'from 2.000 to 3.000'), (3, 'over 3.000')], default=0, verbose_name='Salary range'),
        ),
        migrations.AlterField(
            model_name='job',
            name='schooling',
            field=models.PositiveIntegerField(blank=True, choices=[('Elementary_School', 'Elementary School'), ('High_school', 'High school'), ('Technologist', 'Technologist'), ('University_education', 'University education'), ("Post_MBA _Master's", "Post / MBA / Master's"), ('Doctorate_degree', 'Doctorate degree')], default=0, verbose_name='Schooling'),
        ),
    ]
