# Generated by Django 4.2.3 on 2023-07-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_application_expected_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='schooling',
            field=models.CharField(blank=True, choices=[('Elementary_School', 'Elementary School'), ('High_school', 'High school'), ('Technologist', 'Technologist'), ('University_education', 'University education'), ("Post_MBA _Master's", "Post / MBA / Master's"), ('Doctorate_degree', 'Doctorate degree')], default='Elementary_School', max_length=250, verbose_name='Schooling'),
        ),
    ]
