# Generated by Django 4.2.3 on 2023-07-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_schooling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='expected_salary',
            field=models.FloatField(blank=True, choices=[(0, 1000), (1, 2000), (2, 3000), (3, 4000)], max_length=255, null=True, verbose_name='Expected salary'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_range',
            field=models.FloatField(blank=True, choices=[(0, 1000), (1, 2000), (2, 3000), (3, 4000)], default=0, verbose_name='Salary range'),
        ),
    ]
